//
//  ClipboardFilter.swift
//  DropNest
//
//  Created on 2026-08-07.
//  Privacy red line: decides whether a pasteboard change may enter history.
//

import AppKit
import Defaults
import Foundation

enum ClipboardFilter {

    /// Types that signal "do not record" — set by password managers and
    /// apps producing one-time / auto-generated clipboard content.
    static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    /// File-promise types carry no real data until a drop happens — a copy
    /// consisting only of promises (e.g. dragging out of Finder's cut state
    /// edge cases) must not be recorded as if the file existed.
    static let promiseOnlyTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-url"),
        NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-content"),
        NSPasteboard.PasteboardType("NSFilesPromisePboardType")
    ]

    static func shouldCapture(_ pb: NSPasteboard, sourceAppBundleID: String?) -> Bool {
        // 1. Concealed / transient content — never record, never touch disk.
        let types = pb.types ?? []
        if types.contains(where: concealedTypes.contains) { return false }

        // 2. User ignored source apps.
        if let bundleID = sourceAppBundleID,
           Defaults[.clipboardIgnoredApps].contains(bundleID) { return false }

        // 3. Nothing but file promises — no capturable payload.
        let hasRealContent = types.contains {
            $0 == .string || $0 == .fileURL || $0 == .png || $0 == .tiff
                || $0 == NSPasteboard.PasteboardType("public.url")
        }
        if !hasRealContent { return false }

        return true
    }

    /// Enforces the per-item size cap (Defaults, MB). Image payloads are the
    /// dominant size factor; RTF/HTML are counted too.
    static func withinSizeLimit(imageData: Data?, rtfData: Data?, htmlData: Data?, text: String?) -> Bool {
        let limit = Defaults[.clipboardMaxItemSizeMB] * 1024 * 1024
        var total = imageData?.count ?? 0
        total += rtfData?.count ?? 0
        total += htmlData?.count ?? 0
        total += text?.utf8.count ?? 0
        return total <= limit
    }
}
